---
AWSTemplateFormatVersion: "2010-09-09"

Description: >-
  A sample template with an Instance

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: >-
      Name of the KeyPair to use for the AutoScaling Group
  ImageId:
    Type: AWS::EC2::Image::Id
    Default: ami-9398d3e0

  ApplicationName:
    Type: String
    Default: "Test"

  NTPServer:
    Type: String
    Default: "0.europe.pool.ntp.org"
  VPCName:
    Type: String
    AllowedValues:
    - "Prod"
    - "Dev"
    Default: "Dev"

  InstanceType:
    Type: String
    Default: t2.micro

Mappings:
  applications:
    Test:
      iamRoleName: "role"

Resources:
  ec2Test:
    Type: "AWS::EC2::Instance"
    Properties:
      EbsOptimized: False
      KeyName: !Ref KeyName
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      SecurityGroups:
        - "sg-cb5153ac"
      UserData:
        Fn::Base64:
          Fn::Join:
          - ""
          - - "#!/bin/env bash\n"
            - "ntpdate -u "
            - !Ref NTPServer
            - "\n"
            - "export PATH=$PATH:/opt/aws/bin:/usr/local/bin \n"
            - "# Run /opt/aws/bin/cfn init\n"
            - "/opt/aws/bin/cfn-init --stack "
            - !Ref AWS::StackName
            - " -r lcGPU "
            - " --region "
            - !Ref AWS::Region
            - " --role="
            - Fn::Join:
              - ""
              - - Fn::FindInMap:
                  - "applications"
                  - !Ref ApplicationName
                  - "iamRoleName"
                - !Ref VPCName
            - " || error_exit 'Failed to run /opt/aws/bin/cfn-init'\n"

Outputs:
  ASG:
    Description: AutoScaling Group
    Value: !Ref ec2Test

