---
AWSTemplateFormatVersion: "2010-09-09"

Description: >-
  A sample template with an Instance

Parameters:
  KeyName:
    Type: AWS::EC2::KeyPair::KeyName
    Description: >-
      Name of the KeyPair to use for the AutoScaling Group
  ImageId:
    Type: AWS::EC2::Image::Id
    Default: ami-9398d3e0

  ApplicationName:
    Type: String
    Default: "Test"

  NTPServer:
    Type: String
    Default: "0.europe.pool.ntp.org"
  VPCName:
    Type: String
    AllowedValues:
    - "Prod"
    - "Dev"
    Default: "Dev"

  InstanceType:
    Type: String
    Default: t2.micro

Resources:
  ec2Test:
    Type: "AWS::EC2::Instance"
    Metadata:
      AWS::CloudFormation::Init:
        config:
          commands:
            0000-init:
              command: "yum install parted xfsprogs -y || echo Skipped package install"
            0001-part-disk1:
              command: "while true ; do if [ `fdisk -l | grep xvdz | wc -l` -gt 0 ]; then parted -a optimal -s -- /dev/xvdz mklabel gpt mkpart primary 0% 100%; exit 0;  fi ; done"
            0002-part-disk2:
              command: "while true ; do if [ `fdisk -l | grep xvdx | wc -l` -gt 0 ]; then parted -a optimal -s -- /dev/xvdx mklabel gpt mkpart primary 0% 100%; exit 0;  fi ; done"
            0003-pv-disk1:
              command: "pvcreate /dev/xvdz1"
            0004-pv-disk2:
              command: "pvcreate /dev/xvdx1"
            0005-vgcreate-vg01:
              command: "vgcreate vg01 /dev/xvdz1 /dev/xvdx1"
            0006-lvcreate-data:
              command: "lvcreate vg01 -n data -l50%FREE -i 2 -I64"
            0007-format-data:
              command: "mkfs.xfs -f /dev/mapper/vg01-data"
            0008-create-data-dir:
              command: "mkdir -p /var/lib/data"
            0009-add-data-to-fstab:
              command: "echo /dev/mapper/vg01-data /var/lib/data xfs defaults 0 0 >> /etc/fstab"
            0010-mount-all:
              command: "mount -a"
            0011-set-lvm-flag:
              command: "parted -s -- /dev/xvdz set 1 lvm on ; parted -s -- /dev/xvdx set 1 lvm on"

    Properties:
      IamInstanceProfile: !Ref iamInstanceProfile
      EbsOptimized: False
      KeyName: !Ref KeyName
      ImageId: !Ref ImageId
      InstanceType: !Ref InstanceType
      SecurityGroupIds:
        - "sg-cb5153ac"
      Volumes:
        - VolumeId: !Ref ebsDisk1
          Device: /dev/xvdz
        - VolumeId: !Ref ebsDisk2
          Device: /dev/xvdx
      AvailabilityZone:
        Fn::Select:
          - 0
          - !GetAZs
      SubnetId: "subnet-cb822a93"
      UserData:
        Fn::Base64:
          Fn::Join:
          - "\n"
          - - "#!/bin/env bash"
            - ""
            - Fn::Join:
                - " "
                - - "ntpdate -u"
                  - !Ref NTPServer
            - ""
            - "export PATH=$PATH:/opt/aws/bin:/usr/local/bin"
            - "# Script to initialize the resource with CloudFormaton init tools"
            - "function success_exit"
            - "{"
            - " echo Successfully initialized the resource"
            - " echo Signaling CloudFormation"
            - Fn::Join:
                - " "
                - - " /opt/aws/bin/cfn-signal -e 0 -r \"$1\""
                  - Fn::Join:
                      - "'"
                      - - ""
                        - !Ref WHInstanceInit
                        - ""
            - ""
            - " exit 1"
            - "}"
            - ""
            - "function error_exit"
            - "{"
            - " echo Failure at initializing the resource"
            - " echo Signaling CloudFormation"
            - Fn::Join:
                - " "
                - - " /opt/aws/bin/cfn-signal -e 1 -r \"$1\""
                  - Fn::Join:
                      - "'"
                      - - ""
                        - !Ref WHInstanceInit
                        - ""
            - ""
            - " exit 1"
            - "}"
            - ""
            - Fn::Join:
                - " "
                - - "/opt/aws/bin/cfn-init --stack"
                  - !Ref AWS::StackName
                  - " -r ec2Test"
                  - " --region"
                  - !Ref AWS::Region
                  - " --role"
                  - !Ref iamRole
                  - "&& success_exit \"Resource successfully initlaized\""
                  - "|| error_exit \"Failed to initialize the resource\""
            - ""

  ebsDisk1:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone:
        Fn::Select:
          - 0
          - !GetAZs
      AutoEnableIO: False
      Encrypted: False
      Size: 10
      Tags:
        - Key: Name
          Value: Disk1
        - Key: Usage
          Value: Demo
      VolumeType: standard

  ebsDisk2:
    Type: AWS::EC2::Volume
    Properties:
      AvailabilityZone:
        Fn::Select:
          - 0
          - !GetAZs
      AutoEnableIO: False
      Encrypted: False
      Size: 10
      Tags:
        - Key: Name
          Value: Disk2
        - Key: Usage
          Value: Demo
      VolumeType: standard


  WHInstanceInit:
    Type: "AWS::CloudFormation::WaitConditionHandle"

  WCInstanceInit:
    Type: "AWS::CloudFormation::WaitCondition"
    Properties:
      Handle: !Ref WHInstanceInit
      Timeout: "1800"

  iamRole:
    Type: "AWS::IAM::Role"
    Properties:
      AssumeRolePolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Principal:
              Service: "ec2.amazonaws.com"
            Action: "sts:AssumeRole"

  iamInstanceProfile:
    Type: "AWS::IAM::InstanceProfile"
    Properties:
      Roles:
        - !Ref iamRole

  iamPolicyCFAllow:
    Type: "AWS::IAM::Policy"
    Properties:
      Roles:
        - !Ref iamRole
      PolicyName:
        Fn::Join:
          - "-"
          - - "allowCfSignal"
            - !Ref AWS::StackName
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Effect: "Allow"
            Resource: "*"
            Action:
              - "sts:AssumeRole"
          - Effect: "Allow"
            Action:
              - "cloudformation:SignalResource"
              - "cloudformation:ListStackResources"
              - "cloudformation:DescribeStackResources"
              - "cloudformation:DescribeStackResource"
              - "cloudformation:DescribeStackEvents"
            Resource:
              - Fn::Join:
                  - ""
                  - - "arn:aws:cloudformation:"
                    - !Ref AWS::Region
                    - ":"
                    - !Ref AWS::AccountId
                    - ":stack/"
                    - !Ref AWS::StackName
                    - "/*"


Outputs:
  Instance:
    Description: >-
      Instance ID
    Value: !Ref ec2Test
  Disk1:
    Description: >-
      Disk 1 ID
    Value: !Ref ebsDisk1
  Disk2:
    Description: >-
      Disk2 ID
    Value: !Ref ebsDisk2
